project_id = "gidjkdtmagxuzhlntlbt"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.eval-transcribe]
    verify_jwt = false
  [functions.og-job]
    verify_jwt = false
