import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Terms() {
  return (
    <div className="min-h-[calc(100vh-4rem)] animate-page-enter">
      <div className="container mx-auto px-4 py-12 sm:py-16">
        <div className="max-w-3xl mx-auto">
          <Button variant="ghost" size="sm" className="-ml-2 gap-1.5 text-muted-foreground mb-6" asChild>
            <Link to="/"><ArrowLeft className="w-4 h-4" />Back to home</Link>
          </Button>

          <h1 className="font-heading text-2xl sm:text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p>

          <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">1. Acceptance of terms</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                By creating an account or using WhatSaid as a guest, you agree to these Terms of Service and our <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link>. If you do not agree, do not use the service.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">2. Service description</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                WhatSaid provides AI-powered audio transcription, summarisation, and custom text analysis. Outputs are generated by artificial intelligence and may contain errors, omissions, or inaccuracies. They should not be relied upon as verbatim legal, medical, or official records.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">3. Recording consent — your responsibility</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                You are solely responsible for ensuring that any audio you upload was recorded in compliance with all applicable laws, including obtaining consent from all recorded individuals where required. Recording consent laws vary by jurisdiction (including one-party vs. all-party consent requirements). WhatSaid does not verify recording consent and accepts no liability for recordings made without proper authorisation.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">4. Acceptable use</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">You agree not to:</p>
              <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-5 space-y-1">
                <li>Upload recordings made without the consent of recorded parties where consent is required by law</li>
                <li>Use the service for surveillance, covert monitoring, or any illegal purpose</li>
                <li>Upload content that violates any applicable law or third-party rights</li>
                <li>Attempt to abuse, overload, or interfere with the service</li>
              </ul>
              <p className="text-sm text-muted-foreground leading-relaxed mt-2">
                We reserve the right to suspend or terminate accounts that violate these terms.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">5. Credits and payments</h2>
              <ul className="text-sm text-muted-foreground leading-relaxed list-disc pl-5 space-y-1">
                <li>Credits are prepaid and do not expire</li>
                <li>Guest one-off payments are non-refundable once processing has started</li>
                <li>If a job fails due to a service error, credits will be returned to your balance automatically</li>
                <li>All prices are displayed before purchase and processing</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">6. AI output disclaimer</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                All outputs — including transcripts, summaries, speaker labels, and custom analysis — are generated by AI and are provided "as is". WhatSaid does not guarantee the accuracy, completeness, or fitness for purpose of any output. Speaker identification is approximate and should not be treated as definitive attribution.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">7. Data and privacy</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Your use of WhatSaid is also governed by our <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link>. Audio files are deleted immediately after processing. Transcripts and outputs are retained as described in the Privacy Policy.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">8. Limitation of liability</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                To the maximum extent permitted by law, WhatSaid and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service, including but not limited to damages arising from AI output inaccuracies or recording consent issues.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">9. Age requirement</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                You must be at least 18 years old to use WhatSaid.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">10. Changes to terms</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                We may update these terms from time to time. Continued use of the service constitutes acceptance of updated terms. Material changes will be communicated to account holders.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-lg font-semibold mb-2">11. Contact</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                For questions about these terms, please contact us at the email address provided in the application.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
